// tslint:disable-next-line
export type Movie = {
  budget: number,
  genre: string,
  genres: string[],
  homepage: string,
  id: number,
  imdb_id: string,
  original_language: string,
  overview: string,
  popularity: number,
  poster_path: string,
  production_countries: object[],
  release_date: Date | null,
  release_year: number,
  revenue: number,
  runtime: number,
  status: string,
  tagline: string | undefined,
  title: string,
  video: string,
  vote_average: number,
  vote_count: number,
};
